# Alert when the rate of events exceeds a threshold

# (Optional)
# Elasticsearch host
# es_host: elasticsearch.example.com

# (Optional)
# Elasticsearch port
# es_port: 14900

# (OptionaL) Connect with SSL to Elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for Elasticsearch
#es_username: someusername
#es_password: somepassword
doc_type: "nginx_logs"
# (Required)
# Rule name, must be unique
name: API 404 Count
#use_terms_query: true
# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: frequency
use_count_query: true

# (Required)
# Index to search, wildcard supported
index: nginx-*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
num_events: 5

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
  minutes: 3

#run_every:
 # minutes: 3
realert:
  seconds: 120
# (Required)
# A list of Elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guidei/en/elasticsearch/reference/current/query-dsl.html
filter:
- term:
    status: "404"
- terms:
    url: ["url1", "url2"]
alert_subject: "API 404 Count Alert"
include: ["url"]

# (Required)
# The alert is use when a match is found
alert:
- "slack"
slack:
# The <"https://xxxxx.slack.com/services/new/incoming-webhook"> webhook URL that includes your auth data and the ID of the channel (room) you want to post to.
slack_webhook_url: "x.x.x.x"
