name: "Heartbeat flatline Alert for url"
type: flatline
index: "nginx-*"

threshold: 100

timeframe:
  minutes: 10

query_delay:
  minutes: 2

realert:
  minutes: 5

alert_subject: "Heartbeat Flatline Alert"
alert_text: "Flatline alert for nginx having count {0}"
alert_text_type: alert_text_only
alert_text_args:
- count

alert:
- "slack"
slack:
# The <"https://xxxxx.slack.com/services/new/incoming-webhook"> webhook URL that includes your auth data and the ID of the channel (room) you want to post to.
slack_webhook_url: "<enter slack url here>"
